# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
#    url: jdbc:p6spy:h2:mem:test
    username: root
    password: test

# MP配置
mybatis-plus:
  global-config:
    db-config:
      # 删除时 update user set deleted=1 where id =1 and deleted=0
      # 查找时 select * from user where deleted=0
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 支持统配符 * 或者 ; 分割
  type-enums-package: com.myz.springboot2mybatisplus.enums
  configuration:
    # 3.0.8之前版本问题默认将枚举注册为EnumOrdinalTypeHandler,这是错误的方式,默认是 org.apache.ibatis.type.EnumTypeHandler
    # 如果项目之中实体统一使用IEnum或注解的方式,可配置成 com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler,也可省略上面的type-enums-package配置
    # 配置type-enums-package只对注解方式的枚举处理能提前加载缓存.
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  # 扫描xml文件配置
  mapper-locations: classpath:mapper/*.xml

# Logger Config
logging:
  level:
    com.myz.springboot2mybatisplus: debug