#spring:
#  shardingsphere:
#    datasource:
#      names: master,slave0,slave1,slave2
#      dataSourceMap:
#
#        master：
#          type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/ds_master?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#          username: root
#          password: root
#
#        slave0：
#          type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/ds_master?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#          username: root
#          password: root
#
#        slave1：
#          type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/ds_slave0?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#          username: root
#          password: root
#
#        slave2：
#          type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/ds_slave2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#          username: root
#          password: root
#
#    masterslave:  # 读写分离配置
#      name: ds_ms
#      masterDataSourceName: ds_master
#      slaveDataSourceNames:
#        - ds_slave0
#        - ds_slave1
#        - ds_slave2
#      loadBalanceAlgorithmType: RANDOM
#      props:
#        sql.show: true