spring:
  profiles:
    active: test

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    # 不加这句则默认为myisam引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 打印SQL语句
    show-sql: true
    database: mysql

# mybatis配置
# mybatis:
#  # map文件
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.myz.springboot2.entity

# 监控端点，默认关闭的，开放所有接口
management:
  endpoints:
    web:
      exposure:
        include: "*"