#server:
#  port: 8888eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 10
#  client:
#    registry-fetch-interval-seconds: 5
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/management:

spring:
  application:
    name: spring-boot-admin-server

server:
  port: 8082
