spring:

  datasource:
    #  数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      # 监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      keep-alive: true
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
        allow: ""
        deny: "127.0.0.1"
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          enabled: true
          config:
            multi-statement-allow: true
            delete-allow: true
        slf4j:   # slf4j记录日志
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml