spring:
  application:
    name: spring-boot-service

  boot:
    admin:
      client:
        url: http://localhost:8082 # 注册到指定中心

# 端口号
server:
  port: 8081

# 开放所有监控接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: always