# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.188.33:3306/mybatis-plus?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: maoyz
    password: 123456


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: enabled # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1  # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0
  # 扫描xml文件配置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 日志实现


# Logger Config
logging:
  level:
    com.myz.springboot2.mybatisplus34: debug
