DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	ageEnum INT(3) NULL DEFAULT NULL COMMENT '年龄1',
	gender INT(2) NULL DEFAULT NULL COMMENT '性别,0:MALE, 1:FEMALE',
	grade INT(3) NULL DEFAULT NULL COMMENT '年级',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	is_delete INT(11) NOT NULL DEFAULT 0 COMMENT '是否删除',
	operator VARCHAR(30) NULL DEFAULT NULL COMMENT '操作员',
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS emp;
CREATE TABLE emp
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	version INT(8) NULL COMMENT '版本',
	PRIMARY KEY (id)
);