eureka:
  instance:
    hostname: springboot2-admin-eureka-server
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    # admin的登录账户
    metadata-map:
      user.name: ${spring.security.user.name}
      user.passpord: ${spring.security.user.password}

  client:
    registry-fetch-interval-seconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: springboot2-admin-eureka-server

  #
  security:
    user:
      name: root
      password: root

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
