# 总配置环境
spring:
  profiles:
#   调用dev环境
    active: dev


# 集成JSP
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp


# freemarker配置
  freemarker:
    request-context-attribute: req  #req访问request
    content-type: text/html
    enabled: true
    cache: true  #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    suffix: .ftl   #后缀名
    charset: UTF-8 #编码格式
    settings:
        number_format: '0.##'   #数字格式化，无小数点


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/test
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.example.config.MySqlUpperCaseStrategy #  命名策略
    show-sql: true


#management:
#  security:
#
#    #是否启用安全
#    enabled: true
#endpoints:
#  shutdown:
#  #开启shutdown端点
#  enabled: true



mybatis:
#  mybatis.config-locations=classpath: mybatis/mybatis-config.xml
  # xml文件扫描位置
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.entity

#  分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
