# Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo:
  provider:
    group: ${spring.profiles.active}
    version: 1.0.0
    filter: -exception  # 过滤ExceptionFilter
    retries: 3
    delay: -1
    timeout: 5000
  consumer:
    group: ${spring.profiles.active}
    version: 1.0.0
    check: false
    retries: 3
    timeout: 5000
    mock: fail:return null   # 配置服务降级
  # Dubbo Application
  ## The default value of dubbo.application.name is ${spring.application.name}
  application:
    name: ${spring.application.name}

  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}  # zk
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache

embedded:
  zookeeper:
    port: 2181