xxl:
  job:
    executor:
      adminAddresses: http://127.0.0.1:8080/xxl-job-admin
      accessToken:
      appname: xxl-job-executor-sample
      address:
      ip:
      port: 9998
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
