spring:
  flyway:
    enabled: true
    encoding: UTF-8
    check-location: true
    locations: ["classpath:db/migration"]
    table: flyway_schema_history
    baseline-on-migrate: true
    validate-on-migrate: true

  datasource:
    url: jdbc:mysql://localhost:13306/springboot2_1?serverTimezone=Asia/Shanghai&amp;useSSL=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true&amp;maxReconnects=10&amp;failOverReadOnly=false&amp;useAffectedRows=true&amp;allowMultiQueries=true&amp;jdbcCompliantTruncation=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root